-- load config
require("basic")
require("keymaps")
require("plugins")

require("config.onedark")
require("config.lualine")
require("config.nvim-tree")
require("config.bufferline")
require("config.indentline")
require("config.comment")
require("config.whichkey")
require("config.autopairs")
require("config.hop")
require("config.telescope")
require("config.toggleterm")
require("config.undotree")
require("config.surround")

require("config.mason")
require("config.fidget")
require("config.nvim-treesitter")
require("lsp.setup")
require("dap.setup")
require("cmp.setup")
--require("autocmd")
require("usercmd")
